# Generated by Django 5.0.3 on 2026-09-22 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CapabilityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(choices=[('NG', 'Nigeria'), ('GH', 'Ghana'), ('KE', 'Kenya'), ('RW', 'Rwanda'), ('ZA', 'South Africa'), ('EG', 'Egypt'), ('OTHER', 'Other')], default='NG', max_length=10)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('industry', models.CharField(choices=[('Agriculture', 'Agriculture'), ('Technology', 'Technology'), ('Manufacturing', 'Manufacturing'), ('Logistics', 'Logistics'), ('Healthcare', 'Healthcare'), ('Education', 'Education'), ('Finance', 'Finance'), ('Creative', 'Creative industries'), ('Research', 'Research'), ('Natural resources', 'Natural resources')], default='Agriculture', max_length=50)),
                ('products_services', models.TextField(blank=True)),
                ('skills_expertise', models.TextField(blank=True)),
                ('offers', models.TextField(help_text='What they can offer')),
                ('needs', models.TextField(blank=True, help_text='What they need')),
                ('partnership_type', models.CharField(blank=True, max_length=100)),
                ('target_countries', models.JSONField(blank=True, default=list)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
