# Generated by Django 5.0.3 on 2026-09-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capabilityprofile',
            name='verification_requested',
            field=models.BooleanField(default=False),
        ),
    ]
