# Generated by Django 5.0.3 on 2026-09-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_capabilityprofile_verification_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='capabilityprofile',
            name='avatar_url',
            field=models.URLField(blank=True, default='', help_text='Optional logo/photo URL'),
        ),
    ]
