# Generated by Django 5.0.3 on 2026-09-22 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_capabilityprofile_avatar_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='capabilityprofile',
            name='registration_number',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='capabilityprofile',
            name='registry_name',
            field=models.CharField(blank=True, help_text='e.g. CAC Nigeria, Registrar General Ghana, RDB Rwanda', max_length=120),
        ),
        migrations.AddField(
            model_name='capabilityprofile',
            name='registry_verified',
            field=models.BooleanField(default=False, help_text='Admin confirms the business registry entry'),
        ),
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('target_country', models.CharField(blank=True, choices=[('NG', 'Nigeria'), ('GH', 'Ghana'), ('KE', 'Kenya'), ('RW', 'Rwanda'), ('ZA', 'South Africa'), ('EG', 'Egypt'), ('OTHER', 'Other')], default='', max_length=10)),
                ('industry', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcasts', to=settings.AUTH_USER_MODEL)),
                ('author_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcasts', to='profiles.capabilityprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('milestone', 'Operational milestone'), ('shipment', 'Trade & shipment proof'), ('certification', 'Certification & quality'), ('partnership', 'Partnership announcement')], default='milestone', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('detail', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='profiles.capabilityprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
